# Installs latest release of Node and our dependencies
install:
  - ps: Install-Product node
  - npm install

# Run tests once install is complete
test_script:
  - node --version
  - npm --version
  - npm test

# We don't need to build anything, just run tests
build: off
